KooliProjekt/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt.Data;
using KooliProjekt.Services;
using Microsoft.AspNetCore.Authorization;

namespace KooliProjekt.Controllers
{
    
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        // GET: Customer
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
              return View(await _customerService.GetCustomerAsync());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminPanel()
        {
            return View();
        }
        // GET: Customer/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }


        // GET: Customer/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _customerService.Save(id, customer);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_customerService.Existance(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _customerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

KooliProjekt/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt.Data;
using KooliProjekt.Services;
using Microsoft.AspNetCore.Authorization;

namespace KooliProjekt.Controllers
{
    public class InvoiceController : Controller
    {
        

        private readonly IInvoiceService _invoiceService;
        private readonly IProductService _productService;
        private readonly ICustomerService _customerService;
        private readonly IOrderService _orderService;

        public InvoiceController(IOrderService orderService, IInvoiceService invoiceService, IProductService productService, ICustomerService customerService)
        {
            _invoiceService = invoiceService;
            _productService = productService;
            _customerService = customerService;
            _orderService = orderService;
        }

        // GET: Invoice
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index(int page = 1)
        {
            var result = await _invoiceService.List(page, 5);
            return View(result);
            //return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Myinvoices()
        {
            string loggedInUsername = User.Identity.Name; // Get the logged-in username

            // Retrieve the orders and the products for the logged-in user
            List<Invoice> invoices = await _invoiceService.GetCustomerInvoices(loggedInUsername);

            List<Myinvoice> myinvoices = invoices.Select(o => new Myinvoice {
                Id = o.Id,
                ProductName = o.Product.CarName,
                TotalPrice = o.TotalPrice,
                CustomerId = o.Customer.Name,
                PayStatus = o.PayStatus,
                DistanceDriven = o.DistanceDriven,
            }).ToList();
            // Map the orders and products to the ViewModel
            
            return View(myinvoices);
        }

        // GET: Invoice/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue || !_invoiceService.Existance(id.Value))
            {
                return NotFound();
            }

            var invoice = await _invoiceService.GetById(id.Value);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: Invoice/Create

        public async Task<IActionResult> Create(int? productId, int? orderId)
        {
            var inv = new Invoice();
            if(User.IsInRole("Admin"))
            {
                ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name");
                ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name");
                return View();
            }
            else
            {
                Random random = new Random();

                int min = 10;
                int max = 1000;
                int randomIntInRange = random.Next(min, max);


                var userId = User.Identity.Name;
                inv.Customer = await _customerService.GetByEmail(userId);
                inv.CustomerId = inv.Customer.Id;
                inv.Product = await _productService.GetById(productId.Value);
                var order = await _orderService.GetById(orderId.Value);
                inv.ProductId = productId.Value;
                inv.DistanceDriven = randomIntInRange;
                inv.PayStatus = false;
                inv.PayBy = DateTime.Today;
                inv.WhenTaken = order.WhenTaken.Value;
                inv.GivenBack = DateTime.Now;

                TimeSpan timeDifference = inv.GivenBack.Value.Subtract(inv.WhenTaken.Value);

                decimal durationInDecimal = (decimal)timeDifference.TotalDays;

                inv.TotalPrice = Math.Round(durationInDecimal * inv.Product.TimePrice) + (inv.Product.DistancePrice * randomIntInRange);

                await _invoiceService.Save(inv);
                await _orderService.Delete(order.Id);
                return RedirectToAction(nameof(Myinvoices));

                
            }
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,WhenTaken,GivenBack,DistanceDriven,TotalPrice,PayBy,PayStatus,CustomerId")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                await _invoiceService.Save(invoice);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", invoice.ProductId);
            ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoice/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue || !_invoiceService.Existance(id.Value))
            {
                return NotFound();
            }

            if(User.IsInRole("Admin"))
            {
                var invoice = await _invoiceService.GetById(id.Value);
                if (invoice == null)
                {
                    return NotFound();
                }
                ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", invoice.ProductId);
                ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", invoice.CustomerId);
                return View(invoice);
            }
            else
            {
                var invoice = await _invoiceService.GetById(id.Value);
                invoice.PayStatus = true;

                await _invoiceService.Save(invoice); 
                return RedirectToAction(nameof(Myinvoices));

            }

        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,WhenTaken,GivenBack,DistanceDriven,TotalPrice,PayBy,PayStatus,CustomerId")] Invoice invoice)
        {
            if (id != invoice.Id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _invoiceService.Save(invoice);   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_invoiceService.Existance(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", invoice.ProductId);
            ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoice/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue || !_invoiceService.Existance(id.Value))
            {
                return NotFound();
            }

            var invoice = await _invoiceService.GetById(id.Value);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            await _invoiceService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

KooliProjekt/Views/Order/Create.cshtml
@model KooliProjekt.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductEstimatedPrice" class="control-label"></label>
                <input asp-for="ProductEstimatedPrice" class="form-control" />
                <span asp-validation-for="ProductEstimatedPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
                <!--<span asp-validation-for="CustomerId" class="text-danger"></span>-->
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    | <a asp-action="Index">Back to List</a> | 
    <a asp-controller="Customer" asp-action="AdminPanel">Back to Admin Panel</a> |
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KooliProjekt/Views/Order/Delete.cshtml
@model KooliProjekt.Order

@{
    ViewData["Title"] = "Delete";
}
<style>
    dd
    {
        text-align: center;
    }
</style>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.CarName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductEstimatedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductEstimatedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        @if(User.IsInRole("Admin"))
        {

            <a asp-action="Index">Back to List</a>
        }
        @if(!User.IsInRole("Admin"))
        {
            <a asp-action="Myorders">Back to My Orders</a>
        }
    </form>
</div>

KooliProjekt/Views/Order/Details.cshtml
@model KooliProjekt.Order

@{
    ViewData["Title"] = "Details";
}

<style>
    dd
    {
        text-align: center;
    }
</style>
<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.CarName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductEstimatedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductEstimatedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
    </dl>
    
</div>
<div>
    
    |@if(User.IsInRole("Admin")){<a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> <a asp-action="Index">Back to List</a>}  
    @if(!User.IsInRole("Admin")){<a asp-action="Myorders">Back to My Orders</a>}|
</div>

KooliProjekt/Views/Order/Edit.cshtml
@model KooliProjekt.Order

@{
    ViewData["Title"] = "Edit";
}
<style>
    dd
    {
        text-align: center;
    }
</style>
<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductEstimatedPrice" class="control-label"></label>
                <input asp-for="ProductEstimatedPrice" class="form-control" />
                <span asp-validation-for="ProductEstimatedPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if(User.IsInRole("Admin")){<a asp-action="Index">Back to List</a>}
    @if(!User.IsInRole("Admin")){<a asp-action="Myorders">Back to My Orders</a>}
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KooliProjekt/Views/Order/Index.cshtml
@model KooliProjekt.Data.PagedResult<KooliProjekt.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    | <a asp-action="Create">Create New</a> | 
    <a asp-controller="Customer" asp-action="AdminPanel">Back to Admin Panel</a> |
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                CarName
            </th>
            <th>
                EstimatedPrice
            </th>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Results) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.CarName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductEstimatedPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>

@(await Component.InvokeAsync<KooliProjekt.Components.PagerViewComponent>(new { result = Model, viewName = "Default" }))

KooliProjekt/Views/Order/Myorders.cshtml
@model List<KooliProjekt.Data.Myorders>

<h1 style="font-size: xx-large;">Your Orders</h1>

@if(Model.Count == 0)
    {
        <h4>You do not have Orders yet.</h4>
    }

@foreach (var order in Model)
{
    
    @* <div style="float:right;">
        <button style=""><a asp-action="Delete" asp-route-id="@order.Id">Finish Your Order</a></button>
        <img style="float: right; width:100px; height:100px;" src="../Product/Image/@order.ProductId"/>
    </div> *@
    <hr>
    <h3 style="flex: left;">Order Details</h3>
    <hr>
    <div style="display: flex;">
        @* <img style="float: right; width:100px; height:100px;" src="../Product/Image/@order.ProductId"/> *@
        
         <div style="flex-grow: 3; flex:left;">
            <p style="">Customer: @order.CustomerId</p>
            <p style="">Estimated Price: @order.ProductEstimatedPrice</p>
            <p style="">Car Name: @order.ProductName</p>
            <p>What day car is taken: @order.WhenTaken.Date</p>
        </div>

        <div style="float:right; float-grow: 1;">
            <button ><a asp-controller="Invoice"  asp-action="Create" asp-route-orderId="@order.Id" asp-route-productId="@order.ProductId" asp-route-customerId="@User">Finish Your Order</a></button>
            <img style="float: right; width:100px; height:100px;" src="../Product/Image/@order.ProductId"/>
        </div>
       
        
    </div>
}