KooliProjekt/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt.Data;
using KooliProjekt.Services;
using Microsoft.AspNetCore.Authorization;

namespace KooliProjekt.Controllers
{
    
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        // GET: Customer
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
              return View(await _customerService.GetCustomerAsync());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminPanel()
        {
            return View();
        }
        // GET: Customer/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }


        // GET: Customer/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _customerService.Save(id, customer);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_customerService.Existance(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || !_customerService.Existance(id))
            {
                return NotFound();
            }

            var customer = await _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _customerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

KooliProjekt/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt;
using KooliProjekt.Data;
using KooliProjekt.Services;
using Microsoft.AspNetCore.Authorization;


namespace KooliProjekt.Controllers
{
    public class OrderController : Controller
    {

        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private readonly ICustomerService _customerService;
        private readonly IImageService _imageService;

        public string Role { get; private set; }

        public OrderController(IImageService imageService, IOrderService orderService, IProductService productService, ICustomerService customerService)
        {
            _orderService = orderService;
            _productService = productService;
            _customerService = customerService;
            _imageService = imageService;
        }

        // GET: Order
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int page = 1)
        {
            
            return View(await _orderService.List(page, 2));
            
            //return View(await applicationDbContext.ToListAsync());
        }
        public IActionResult Image(int id)
        {
            return File(_imageService.ReadImage(id), "image/jpeg");
            
        }

        public async Task<IActionResult> Myorders()
        {


           string loggedInUsername = User.Identity.Name; // Get the logged-in username


            // Retrieve the orders and the products for the logged-in user
            List<Order> orders = await _orderService.GetCustomerOrders(loggedInUsername);

            List<Myorders> myorders = orders.Select(o => new Myorders
            {
                Id = o.Id,
                ProductName = o.Product.CarName,
                ProductEstimatedPrice = o.ProductEstimatedPrice,
                ProductId = o.ProductId,
                CustomerId = o.Customer.Name,
                WhenTaken = o.WhenTaken.Value
            }).ToList();
            // Map the orders and products to the ViewModel
            
            return View(myorders);
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue || !_orderService.Existance(id.Value))
            {
                return NotFound();
            }

            var order = await _orderService.GetById(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Order/Create
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create([FromQuery] int? productId)
        {
            var r = new Order();
 
            if (!User.IsInRole("Admin"))
            { 
                var userId = User.Identity.Name;
                
                r.Customer = await _customerService.GetByEmail(userId);
                r.CustomerId = r.Customer.Id;
                r.ProductId = productId.Value;
                r.WhenTaken = DateTime.Now;
                r.Product = await _productService.GetById(productId.Value);
                r.ProductEstimatedPrice = r.Product.EstimatedPrice;
                ViewData["ProductId"] = r.Product.CarName;
                ViewData["CustomerId"] = r.Customer.Name;

                await _orderService.Save(r);
                return RedirectToAction(nameof(Myorders));
            }
            else
            {
                
                if (productId.HasValue)
                r.ProductId = productId.Value;
            
            

                ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name");
                ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name");
            
                return View(r);
            }
        }

        // POST: Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,EstimatedPrice,CustomerId")] Order order)
        {
            
            if (ModelState.IsValid)
            {
                await _orderService.Save(order);
                return RedirectToAction(nameof(Index));
            }

            ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", order.ProductId);
            ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", order.CustomerId);
            return View(order);
        }
        

        // GET: Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue || !_orderService.Existance(id.Value))
            {
                return NotFound();
            }

            var order = await _orderService.GetById(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", order.ProductId);
            ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", order.CustomerId);
            return View(order);
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,EstimatedPrice,CustomerId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _orderService.Save(order);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_orderService.Existance(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(await _productService.Lookup(), "Id", "Name", order.ProductId);
            ViewData["CustomerId"] = new SelectList(await _customerService.Lookup(), "Id", "Name", order.CustomerId);
            return View(order);
        }

        // GET: Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue || !_orderService.Existance(id.Value))
            {
                return NotFound();
            }
            
            var order = await _orderService.GetById(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _orderService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

KooliProjekt/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KooliProjekt.Data;
using KooliProjekt;
using KooliProjekt.Services;
using Microsoft.AspNetCore.Authorization;

namespace KooliProjekt.Controllers
{
    public class ProductController : Controller
    {
        

        private readonly IImageService _imageService;

        private readonly IProductService _productService;
        private readonly IOrderService _orderService;

        public ProductController(IImageService imageService, IProductService productService, IOrderService orderService)
        {
            _imageService = imageService;
            _productService = productService;
            _orderService = orderService;
        }



        // GET: Product
        
        public async Task<IActionResult> Index(int page = 1)
        {
            return View(await _productService.List(page, 5));
        }


        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue || !_productService.Existance(id.Value))
            {
                return NotFound();
            }

            var product = await _productService.GetById(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        [HttpGet("create")]
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create([Bind("Id,Brand,Model,Manufacturer,CarNum,CarType,DistancePrice,TimePrice")] Product product, IFormFile image)
        {
            

            if (!ModelState.IsValid)
            {       
                return View(product);
            }
            
            await _productService.Save(product);


            using (var stream = image.OpenReadStream())
            {
                await _imageService.WriteImage(product.Id, stream);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Image(int id)
        {
            return File(_imageService.ReadImage(id), "image/jpeg");
            
        }

    

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue || !_productService.Existance(id.Value))
            {
                return NotFound();
            }

            var product = await _productService.GetById(id.Value);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand,Model,Manufacturer,CarNum,CarType,DistancePrice,TimePrice")] Product product, IFormFile image)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _productService.Save(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_productService.Existance(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                

                if (image != null) 
                {
                    
                    using(var stream = image.OpenReadStream())
                    {
                        await _imageService.UpdateImage(product.Id, stream);
                    }
                }
 
                
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }
        
        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue || !_productService.Existance(id.Value))
            {
                return NotFound();
            }

            var product = await _productService.GetById(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            await _productService.Delete(id);
            return RedirectToAction(nameof(Index));
        }   
    }
}

KooliProjekt/Views/Customer/AdminPanel.cshtml
@model KooliProjekt.Data.Customer

@{
    ViewData["Title"] = "AdminPanel";
}

<h1>Admin Panel</h1>

<div>
    <ul>
        <li>
            <a asp-controller="Customer" asp-action="Index">Customers</a>
        </li>
        <li>
            <a asp-controller="Order" asp-action="Index">Orders</a>
            <ul>
                <li>
                    <a asp-controller="Order" asp-action="Create">Create Order Manualy</a>
                </li>
            </ul>
            
        </li>
        <li>
            <a asp-controller="Product" asp-action="Index">Products</a>
            <ul>
                <li>
                    <a asp-controller="Product" asp-action="Create">Add new Car</a>
                </li>
            </ul>
            
        </li>
        <li>
            <a asp-controller="Invoice" asp-action="Index">Invoices</a>
            <ul>
                <li>
                    <a asp-controller="Invoice" asp-action="Create">Create Invoice Manualy</a>
                </li>
            </ul>
            
        </li>
    </ul>
</div>

KooliProjekt/Views/Customer/Delete.cshtml
@model KooliProjekt.Data.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
       
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KooliProjekt/Views/Customer/Details.cshtml
@model KooliProjekt.Data.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
       
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

KooliProjekt/Views/Customer/Edit.cshtml
@model KooliProjekt.Data.Customer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postcode" class="control-label"></label>
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KooliProjekt/Views/Customer/Index.cshtml
@model IEnumerable<KooliProjekt.Data.Customer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p><a asp-controller="Customer" asp-action="AdminPanel">Back to Admin Panel</a></p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>